=== xxBei/JavaStudy/XML/Example/xmlDemo01/src/xml/stus.dtd
<!--PCDATA 的意思是被解析的字符数据（parsed character data）。-->

<!--<!ELEMENT 元素名称 类别>-->
<!--<!ELEMENT 元素名称 (元素内容)>-->
<!--<!ELEMENT 元素名称 (#PCDATA)>-->
<!--(stu)+ "+"表示里面有多个stu-->
<!ELEMENT stus (stu)+>
<!ELEMENT stu (name,age,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!--给元素添加属性-->
<!--元素名称 属性名称 属性类型 默认值-->
<!ATTLIST stu id ID #IMPLIED>

=== xxBei/JavaStudy/XML&Tomcat/Example/xmlDemo01/out/production/xmlDemo01/xml/stus.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE stus SYSTEM "stus.dtd">
<stus>
    <stu>
        <name>张三</name>
        <age>18</age>
        <address>北京</address>
    </stu>
    <stu>
        <name>张三</name>
        <age>18</age>
        <address>北京</address>
    </stu>
</stus>
