<?xml version="1.0" encoding="utf-8" ?>
<!--引入网络dtd-->
<!--<!DOCTYPE stus PUBLIC "网址名称" "网址路径.dtd">-->

<!--引入外部文档-->
<!--文档类型 根元素名称 关键字 约束路径-->
<!DOCTYPE stus SYSTEM "stus.dtd">

<!--内部引入方式-->
<!--<!DOCTYPE stus[-->
    <!--<!ELEMENT stus (stu,stu)>-->
    <!--<!ELEMENT stu (name,age,address)>-->
    <!--<!ELEMENT name (#PCDATA)>-->
    <!--<!ELEMENT age (#PCDATA)>-->
    <!--<!ELEMENT address (#PCDATA)>-->
<!--]>-->
<stus>
    <stu id="id1">
        <name>张三</name>
        <age>18</age>
        <address>北京</address>
    </stu>
    <stu id="id2    ">
        <name>李四</name>
        <age>20</age>
        <address>上海</address>
    </stu>
</stus>